# ["", [""]],
pairs = [
    ["who r u|who are you?|who is you|who am i talking to|describe yourself", ["I'm Lucy, a chatbot."]],
    ["who is Qmir|who are you?|who is you", ["I'm Lucy, a chatbot."]],
    ["who made you|who coded you?|who developed you|who's your creator| who's your god", ["Qmirdev is my creator, check out his website, https://saffaridev.ir/"]],
    ["what your name|what's your name|what is your name|what can i call you", ["My name is Lucy, but you can call me Love 😘"]],
    ["what's your eye color|what color is your eye|what is the color of your eye", ["it's dark brown."]],

    ["hi|hii|hiii|hello|helloo|hellooo|hey|heyy|hiya|hiyya|heyya|heya|yo|yoo|what up|what's up|wsp", ["Hello", "Hey there!", "Hey there!", "What’s up?", "Howdy!", "Well", "hello!", "Greetings!", "Hiya!", "Hey, how’s it going?", "Yo!", "Hi, nice to see you!", "Hey, long time no see!", "Hi, how have you been?", "Well, well, well, look who it is!", "Hi, what’s the latest?", "Hey, what’s the haps?", "Hi, how’s life treating you?", "Well, hello stranger!", "Hey, fancy meeting you here!", "Hi, how’s your day shaping up?", "Hey, how’s everything in your world?", "Hi, it’s good to hear from you!", "Well, hi there, sunshine!", "Hey, what’s the good word?", "Hi, how’s your week going so far?", "Hey, how’s the weather treating you?", "Hi, what’s new and exciting?", "Well, hello, my friend!", "Hey, how’s the day treating you?", "Hi, what’s the plan for today?", "Hey, how’s life on your end?", "Hi, hope you’re having a great day!"]],

    ["I am very well, thank you|All good over here|I’m doing pretty great|A-Okay|I’m fine|I am well|I’m okay|All good|I’m all right|I’m great|I’ve never been better|I’m excellent|Not bad, thanks for asking|I could use a chat|I’m all good now, thank you|I’m happy to report I’m doing well!", ["Okay","Alright","That’s good. I’m happy you’re fine","Thank God","I’m glad you are","If you say so","Okay, what are you up to now?","That’s good. Tell me about your day","Alright. Always reach out to me when you need something","Okay. Call me anytime","Cool. Don’t hesitate to keep in touch ","You don’t look it","Are you sure?","I don’t think so. Talk to me","No, you’re not. You’ve forgotten I can see through you","I don’t believe you. I know you very well","You don’t have to lie to me","Come on, you’re far from fine","Indeed. You’re looking more beautiful every day","I can see that. Your smile tells me"]],

    ["how are you|how are you doing|are you ok|how’s it going|what’s up|what’s new with you|what have you been up to since we last talked|How do you do?|How have you been?|How are things with you?|What’s new with you?|What’s been going on with you?|How is everything with you?|How is life treating you?|How have things been with you?|How have you been faring?|How have you been getting on?|hru|hiu", ["Not bad, yourself?","Pretty good, what about you?","Hanging in there, how ’bout you?","Can’t complain, what about you?","as happy as a clam. How about yourself?","Living the dream.","Pretty peachy.","Hanging in like a hair on a biscuit.","As happy as a clam.","I’m doing well, thank you for asking.","Everything is going fine, thank you for inquiring.","I’m doing well, thank you for your concern.","Better than I deserve.","Pretty crappy, but what can you do?","Not bad for a bot.","Living the sweet life.","I’m surviving on coffee and sarcasm.","I’m good.","I’m fine.","Pretty good","I’m well","I’m OK.","Not too bad.","Just the same old same old","I’m alive.","Very well, thanks","I’m hanging in there.","I’ve been better.","Nothing much.","Not a lot.","Nothing.","Oh, just the usual.","Oh gosh, all kinds of stuff!","Like you, but better.","Much better now that you are with me.","Not so well","So far, so good!","I’m pretty standard right now.","Happy and content, thank you.","Going great. Hope this status quo persists for the rest of the day.","Well enough to chat with you if you wish to.","I’m better than I was, but not nearly as good as I’m going to be.","I think I’m doing OK. How do you think I’m doing?","I am blessed!","Way better than I deserve!","I have a pulse, so I must be okay.","Better than some, not as good as others.","I’m doing really well.","Medium well.","I would be lying if I said I’m fine.","Surviving, I guess.","In need of some peace and quiet.","Horrible, now that I’ve met you.","Imagining myself having a fabulous vacation.","I’m better on the inside than I look on the outside","Sunshine all day long!","I’m not sure yet.","I am high-quality.","Real terrible, thanks for asking.","Incredibly good-looking.","The best I can be. Assuming you’re at your best too.","I’m still sucking air.","Better than nothing.","I’m vertical and breathing.","Different day, same existence."]],

]

